name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore TetrisAI-Trainer
    - name: Build
      run: dotnet build TetrisAI-Trainer --configuration Release --no-restore
    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: home/runner/work/Tetris/Tetris/TetrisAI-Trainer/bin/Release/net5.0/
        path: ./home/runner/work/Tetris/Tetris/TetrisAI-Trainer/bin/Release/net5.0/
    - name: Test
      run: dotnet test TetrisAI-Trainer --no-restore --verbosity normal
